/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicOffsetsDotjsonRouteImport } from './routes/api/public/offsets[.]json'
import { Route as ApiPublicOffsetsDothppRouteImport } from './routes/api/public/offsets[.]hpp'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOffsetsDotjsonRoute = ApiPublicOffsetsDotjsonRouteImport.update({
  id: '/api/public/offsets.json',
  path: '/api/public/offsets.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOffsetsDothppRoute = ApiPublicOffsetsDothppRouteImport.update({
  id: '/api/public/offsets.hpp',
  path: '/api/public/offsets.hpp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/api/public/offsets.hpp': typeof ApiPublicOffsetsDothppRoute
  '/api/public/offsets.json': typeof ApiPublicOffsetsDotjsonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/api/public/offsets.hpp': typeof ApiPublicOffsetsDothppRoute
  '/api/public/offsets.json': typeof ApiPublicOffsetsDotjsonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/api/public/offsets.hpp': typeof ApiPublicOffsetsDothppRoute
  '/api/public/offsets.json': typeof ApiPublicOffsetsDotjsonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/api/public/offsets.hpp'
    | '/api/public/offsets.json'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/api/public/offsets.hpp'
    | '/api/public/offsets.json'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/api/public/offsets.hpp'
    | '/api/public/offsets.json'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ApiPublicOffsetsDothppRoute: typeof ApiPublicOffsetsDothppRoute
  ApiPublicOffsetsDotjsonRoute: typeof ApiPublicOffsetsDotjsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/offsets.json': {
      id: '/api/public/offsets.json'
      path: '/api/public/offsets.json'
      fullPath: '/api/public/offsets.json'
      preLoaderRoute: typeof ApiPublicOffsetsDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/offsets.hpp': {
      id: '/api/public/offsets.hpp'
      path: '/api/public/offsets.hpp'
      fullPath: '/api/public/offsets.hpp'
      preLoaderRoute: typeof ApiPublicOffsetsDothppRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ApiPublicOffsetsDothppRoute: ApiPublicOffsetsDothppRoute,
  ApiPublicOffsetsDotjsonRoute: ApiPublicOffsetsDotjsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
