/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicOffsetsDotjsonRouteImport } from './routes/api/public/offsets[.]json'
import { Route as ApiPublicOffsetsDothppRouteImport } from './routes/api/public/offsets[.]hpp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOffsetsDotjsonRoute = ApiPublicOffsetsDotjsonRouteImport.update({
  id: '/api/public/offsets.json',
  path: '/api/public/offsets.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOffsetsDothppRoute = ApiPublicOffsetsDothppRouteImport.update({
  id: '/api/public/offsets.hpp',
  path: '/api/public/offsets.hpp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/offsets.hpp': typeof ApiPublicOffsetsDothppRoute
  '/api/public/offsets.json': typeof ApiPublicOffsetsDotjsonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/offsets.hpp': typeof ApiPublicOffsetsDothppRoute
  '/api/public/offsets.json': typeof ApiPublicOffsetsDotjsonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/offsets.hpp': typeof ApiPublicOffsetsDothppRoute
  '/api/public/offsets.json': typeof ApiPublicOffsetsDotjsonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/offsets.hpp' | '/api/public/offsets.json'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/offsets.hpp' | '/api/public/offsets.json'
  id: '__root__' | '/' | '/api/public/offsets.hpp' | '/api/public/offsets.json'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicOffsetsDothppRoute: typeof ApiPublicOffsetsDothppRoute
  ApiPublicOffsetsDotjsonRoute: typeof ApiPublicOffsetsDotjsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/offsets.json': {
      id: '/api/public/offsets.json'
      path: '/api/public/offsets.json'
      fullPath: '/api/public/offsets.json'
      preLoaderRoute: typeof ApiPublicOffsetsDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/offsets.hpp': {
      id: '/api/public/offsets.hpp'
      path: '/api/public/offsets.hpp'
      fullPath: '/api/public/offsets.hpp'
      preLoaderRoute: typeof ApiPublicOffsetsDothppRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicOffsetsDothppRoute: ApiPublicOffsetsDothppRoute,
  ApiPublicOffsetsDotjsonRoute: ApiPublicOffsetsDotjsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
