/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as F4HBNFHRVB34RouteImport } from './routes/F4HBNFHRVB34'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicOffsetsDothppRouteImport } from './routes/api/public/offsets[.]hpp'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const F4HBNFHRVB34Route = F4HBNFHRVB34RouteImport.update({
  id: '/F4HBNFHRVB34',
  path: '/F4HBNFHRVB34',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOffsetsDothppRoute = ApiPublicOffsetsDothppRouteImport.update({
  id: '/api/public/offsets.hpp',
  path: '/api/public/offsets.hpp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/F4HBNFHRVB34': typeof F4HBNFHRVB34Route
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/api/public/offsets.hpp': typeof ApiPublicOffsetsDothppRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/F4HBNFHRVB34': typeof F4HBNFHRVB34Route
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/api/public/offsets.hpp': typeof ApiPublicOffsetsDothppRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/F4HBNFHRVB34': typeof F4HBNFHRVB34Route
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/api/public/offsets.hpp': typeof ApiPublicOffsetsDothppRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/F4HBNFHRVB34'
    | '/admin'
    | '/auth'
    | '/api/public/offsets.hpp'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/F4HBNFHRVB34' | '/admin' | '/auth' | '/api/public/offsets.hpp'
  id:
    | '__root__'
    | '/'
    | '/F4HBNFHRVB34'
    | '/admin'
    | '/auth'
    | '/api/public/offsets.hpp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  F4HBNFHRVB34Route: typeof F4HBNFHRVB34Route
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ApiPublicOffsetsDothppRoute: typeof ApiPublicOffsetsDothppRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/F4HBNFHRVB34': {
      id: '/F4HBNFHRVB34'
      path: '/F4HBNFHRVB34'
      fullPath: '/F4HBNFHRVB34'
      preLoaderRoute: typeof F4HBNFHRVB34RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/offsets.hpp': {
      id: '/api/public/offsets.hpp'
      path: '/api/public/offsets.hpp'
      fullPath: '/api/public/offsets.hpp'
      preLoaderRoute: typeof ApiPublicOffsetsDothppRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  F4HBNFHRVB34Route: F4HBNFHRVB34Route,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ApiPublicOffsetsDothppRoute: ApiPublicOffsetsDothppRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
